// Campus location, from the official Google Maps place listing.
//
// Single source of truth on purpose: Contact and HowToReach each hard-coded their
// own coordinates and had drifted 4.1km and 4.7km away from the campus -- in
// different directions, so they disagreed with each other as well as with reality.
export const CAMPUS = {
  lat: 12.7558347,
  lng: 77.6258919,
  /** Google feature id (ftid) for the S-VYASA Arogyadhama listing. */
  placeId: "0x3bae6910ad19a103:0x8b8a92e7a08d9e21",
  label: "S-VYASA AROGYADHAMA PRASHANTI KUTIRAM, J.Bingipura, Karnataka 560105",
};

// Google's own "Open in Maps" control lives inside the embedded iframe and is
// generated by Google from this URL's data -- so getting these fields right is
// what makes that button open the real place. This keeps the exact `pb=` shape
// Google's "Share -> Embed" emits and only substitutes the location fields;
// the encoding is internal to Google, so a hand-rolled string may not render.
export const MAPS_EMBED_SRC =
  "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3889.734" +
  `!2d${CAMPUS.lng}!3d${CAMPUS.lat}` +
  "!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2" +
  `!1s${encodeURIComponent(CAMPUS.placeId)}` +
  `!2s${encodeURIComponent(CAMPUS.label)}` +
  "!5e0!3m2!1sen!2sin!4v1700000000000";

// Documented Maps URL API. Coordinates rather than a name search, so it always
// lands on the campus instead of resolving fuzzily to whatever matches the text.
export const MAPS_PLACE_URL =
  `https://www.google.com/maps/search/?api=1&query=${CAMPUS.lat},${CAMPUS.lng}`;

export const WAZE_URL = `https://waze.com/ul?ll=${CAMPUS.lat},${CAMPUS.lng}&navigate=yes`;
